version: '3.8'

services:
  yamleditor:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    volumes:
      - ./workspace:/app/workspace  # 挂载到容器内的/app/workspace
    restart: unless-stopped 